# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_page', '0002_contentindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
