# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-07 00:26
from __future__ import unicode_literals

import content_page.models
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('content_page', '0003_auto_20160731_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body_en',
            field=wagtail.wagtailcore.fields.StreamField((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='picture')), ('media', content_page.models.AudioBlock(icon='media')))),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='body_np',
            field=wagtail.wagtailcore.fields.StreamField((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='picture')), ('media', content_page.models.AudioBlock(icon='media')))),
        ),
    ]
