# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_page', '0004_auto_20160807_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='improved_technique',
            field=models.BooleanField(default=True),
        ),
    ]
