# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_page', '0004_auto_20160804_0818'),
        ('content_page', '0004_auto_20160807_0026'),
    ]

    operations = [
    ]
