# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_page', '0005_contentpage_improved_technique'),
        ('content_page', '0005_merge'),
    ]

    operations = [
    ]
