# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, choices=[('Prepare Sunken Bed', 'Prepare Sunken Bed'), ('Prepare leaf pot bed', 'Prepare leaf pot bed'), ('Prepare raised bed', 'Prepare raised bed'), ('Nursery/Garden bed preparation', 'Nursery/Garden bed preparation'), ('Transplant From Nursery Into Garden Bed', 'Transplant From Nursery Into Garden Bed'), ('Sew Seeds Into Garden Bed', 'Sew Seeds Into Garden Bed'), ('Direct Seeding', 'Direct Seeding'), ('Mulch Plant', 'Mulch Plant'), ('Water with 5:1 Water to Urine', 'Water with 5:1 Water to Urine'), ('Water with 3:1 Water to Urine', 'Water with 3:1 Water to Urine'), ('Apply Bio-Pesticide', 'Apply Bio-Pesticide'), ('Apply Compost/FYM', 'Apply Compost/FYM'), ('Water Plant', 'Water Plant'), ('Build Staking For Plant', 'Build Staking For Plant'), ('Clear Out Old Plants', 'Clear Out Old Plants'), ('Water Seed Bed', 'Water Seed Bed'), ('Thin Direct Seeded Plants', 'Thin Direct Seeded Plants'), ('Water Vegetable Bed with 5:1 Water to Urine', 'Water Vegetable Bed with 5:1 Water to Urine'), ('Start Plastic Covered Nursery', 'Start Plastic Covered Nursery')], default='', max_length=100)),
                ('week', models.CharField(blank=True, choices=[('Week 1', 'Week 1'), ('Week 2', 'Week 2'), ('Week 3', 'Week 3'), ('Week 4', 'Week 4')], default='', max_length=20)),
                ('month', models.CharField(blank=True, choices=[('Baisakh', 'Baisakh'), ('Jestha', 'Jestha'), ('Ashar', 'Ashar'), ('Shrawan', 'Shrawan'), ('Bhadra', 'Bhadra'), ('Ashoj', 'Ashoj'), ('Karthik', 'Karthik'), ('Mangshir', 'Mangshir'), ('Poush', 'Poush'), ('Magh', 'Magh'), ('Falgun', 'Falgun'), ('Chaitra', 'Chaitra')], default='', max_length=30)),
                ('remark', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=60)),
                ('remark_about_plant', models.TextField(blank=True, default='')),
                ('last_changed_by', models.CharField(blank=True, max_length=30, null=True)),
                ('events', models.ManyToManyField(blank=True, null=True, to='metadataapp.Event')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('kg_per_bio_intensive_bed', models.TextField(blank=True, default='')),
                ('cost_per_kg', models.TextField(blank=True, default='')),
                ('nutrition', models.TextField(blank=True, default='')),
                ('seed_availability', models.TextField(blank=True, default='')),
                ('common_pest', models.TextField(blank=True, default='')),
                ('jhol_mal_recipe', models.TextField(blank=True, default='')),
                ('compost', models.TextField(blank=True, default='')),
                ('planting_distance', models.TextField(blank=True, default='')),
                ('planting_date', models.TextField(blank=True, default='')),
                ('planting_depth', models.TextField(blank=True, default='')),
                ('alternatives', models.TextField(blank=True, default='')),
                ('soil_preparation', models.TextField(blank=True, default='')),
                ('seed_rate', models.TextField(blank=True, default='')),
                ('water_requirement', models.TextField(blank=True, default='')),
                ('intercultural_operation', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='plant_events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadataapp.Plant'),
        ),
    ]
