# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadataapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='detailURL',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='plant',
            name='season',
            field=models.CharField(blank=True, choices=[('summer', 'summer'), ('rainy', 'rainy'), ('winter', 'winter')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='plant',
            name='unique_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
