# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 01:21
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadataapp', '0006_event_nepali_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=7)),
            ],
        ),
    ]
